# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.10
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

package MadgwickAHRS;
use base qw(Exporter);
use base qw(DynaLoader);
package MadgwickAHRSc;
bootstrap MadgwickAHRS;
package MadgwickAHRS;
@EXPORT = qw();

# ---------- BASE METHODS -------------

package MadgwickAHRS;

sub TIEHASH {
    my ($classname,$obj) = @_;
    return bless $obj, $classname;
}

sub CLEAR { }

sub FIRSTKEY { }

sub NEXTKEY { }

sub FETCH {
    my ($self,$field) = @_;
    my $member_func = "swig_${field}_get";
    $self->$member_func();
}

sub STORE {
    my ($self,$field,$newval) = @_;
    my $member_func = "swig_${field}_set";
    $self->$member_func($newval);
}

sub this {
    my $ptr = shift;
    return tied(%$ptr);
}


# ------- FUNCTION WRAPPERS --------

package MadgwickAHRS;

*MadgwickAHRSupdate = *MadgwickAHRSc::MadgwickAHRSupdate;
*MadgwickAHRSupdateIMU = *MadgwickAHRSc::MadgwickAHRSupdateIMU;
*init_q = *MadgwickAHRSc::init_q;

# ------- VARIABLE STUBS --------

package MadgwickAHRS;

*q0 = *MadgwickAHRSc::q0;
*q1 = *MadgwickAHRSc::q1;
*q2 = *MadgwickAHRSc::q2;
*q3 = *MadgwickAHRSc::q3;
1;
